version: '4.29.0'
services:
  db:
    container_name: "db"
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwer12asd
      - POSTGRES_DB=education_db
    ports:
      - "5555:5432"
    networks:
      - custom

  db_test:
    container_name: "db_test"
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=qwer12asd_test
      - POSTGRES_DB=education_db_test
    ports:
      - "5556:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge
